apiVersion: v1
kind: Pod
metadata:
  name: rabbitmq
  labels:
    name: rabbitmq
spec:
  containers:
    - name: rabbitmq
      image: tutum/rabbitmq
      env:
        - name: RABBITMQ_PASS
          value: rabbit-1f2d1e2e67df
      ports:
        - name: userport
          containerPort: 5672
        - name: adminport
          containerPort: 15672